
navsat_transform:
  ros__parameters:
    frequency: 400.0
    delay: 0.0
    magnetic_declination_radians: 0.0514872  # For lat/long 55.944831, -3.186998
    yaw_offset: 0.0 #1.570796327  # IMU reads 0 facing magnetic north, not east
    zero_altitude: true
    broadcast_cartesian_transform: true
    publish_filtered_gps: false
    use_odometry_yaw: false
    wait_for_datum: false
    use_local_cartesian: true # critical to use local ENU