/odom/ackermann_node:
  ros__parameters:
    steering_angle_fb_topic: '/feedback/steer_angle'
    wheelspeed_fb_topic: '/feedback/wheelspeed'
    output_topic: '/odometry/wheel'
    parent_frame: 'odom'
    child_frame: 'base_link'
    use_sim_time: true