/perception/lane_detection_node:
  ros__parameters:
    image_source_topic: '/cameras/front_raw'
    image_output_topic: '/perception/front_lane_detected'

/perception/pedestrian_detector_node:
  ros__parameters:
    image_source_topic: '/cameras/front_raw'
    image_output_topic: '/perception/image_front_pedestrian'
    hue_upper: 15
    hue_lower: 5
    sat_upper: 230
    sat_lower: 110
    val_upper: 230
    val_lower: 70
