
/sensors/cameras/bfly_center:
  ros__parameters:
    serial_no: '18295828' #'18295827' #
    pixel_format: 'RGB8Packed'
    video_mode: 'Mode1'
    raw_image_topic: '/sensors/cameras/center/image'
    compress_image: True

/sensors/cameras/bfly_left:
  ros__parameters:
    serial_no: '18295825'
    pixel_format: 'RGB8Packed'
    video_mode: 'Mode1'
    raw_image_topic: '/sensors/cameras/left/image'

/sensors/cameras/bfly_right:
  ros__parameters:
    serial_no: '18295818'
    pixel_format: 'RGB8Packed'
    video_mode: 'Mode1'
    raw_image_topic: '/sensors/cameras/right/image'