
navsat_transform:
  ros__parameters:
    frequency: 60.0
    delay: 0.0
    magnetic_declination_radians: 0.0514872  # For lat/long 55.944831, -3.186998
    yaw_offset: 0.0 #1.570796327  # IMU reads 0 facing magnetic north, not east
    zero_altitude: true
    broadcast_cartesian_transform: true
    #broadcast_utm_transform: true    # This syntax is depreciated, use broadcast_cartesian_transform instead
    publish_filtered_gps: false
    use_odometry_yaw: false
    wait_for_datum: false
    use_local_cartesian: true # critical to use local ENU

navsat_odom_node:
  ros__parameters:
    use_fake_odom: false
    tf_frequency: 50.0
    #expected_lat: 36.1156
    #expected_lon: -97.0584
    #expected_lat: 42.668419
    #expected_lon: -83.217991
    initial_ll_radius: 10000.0