
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 15.0
      publish_frequency: 20.0
      global_frame: map                  
      robot_base_frame: base_link
      trinary_costmap: True
      use_sim_time: False
      rolling_window: True
      width: 20
      height: 20
      resolution: 0.05
      robot_radius: 3.46
      plugins: ["inflation_layer"] #, "voxel layer]"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.0
        inflation_radius: 1.5
        enabled: true
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: false
        publish_voxel_map: false
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /sensors/lidar/front_lidar/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 15.0
      publish_frequency: 15.0
      global_frame: map
      robot_base_frame: base_link
      width: 50
      height: 50
      origin_x: -25.0
      origin_y: -25.0
      use_sim_time: False
      robot_radius: 3.46
      resolution: 0.1
      track_unknown_space: False
      plugins: ["static_layer", "inflation_layer", "obstacle_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: hokuyo_front_scan
        max_obstacle_height: 2.0
        hokuyo_front_scan:
          topic: /sensors/lidar/front_lidar/scan
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          clearing: True
          marking: True
          data_type: "LaserScan" 
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        cost_scaling_factor: 2.0
        inflation_radius: 0.55
        inflate_unknown: False
        inflate_around_unknown: false
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: False
        subscribe_to_updates: true
        transform_tolerance: 0.1
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False


map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: /home/joyride-obc/joyride-ros-main/src/joyride_bringup/maps/empty_map.yaml

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5000
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: False