# Configures the diagnostics software; sets what nodes are required and what nodes to keep track of
automode_manager_server:
  ros__parameters:

    # List all nodes here. Roundabout but required (as far as I know)
    tracked_nodes:
      - drive_controller
      - accessory_controller
      - power_steering
      - polaris_gem
      - automode
      - roscan
      - static_tf
      - odom
      - cpu
      - ram


    # Describe nodes here
    automode:
      name: /servers/automode_manager
      id: 0xa0
      require: True
    roscan:
      name: /servers/roscan_interface
      id: 0xa1
      require: True
    static_tf:
      name: /servers/static_broadcaster
      id: 0xa2
      require: False
    odom:
      name: 'navsat_odom_node: /sensors/gps_odom'
      id: 0xf0
      require: True
    drive_controller:
      name: /dbw/drive_controller
      id: 0xc0
      require: False
    accessory_controller:
      name: /dbw/accessory_controller
      id: 0xc1
      require: False
    power_steering:
      name: /dbw/power_steering
      id: 0xc2
      require: True
    polaris_gem:
      name: /dbw/polaris_gem
      id: 0xc3
      require: True
    cpu:
      name: /utility/cpu
      id: 0xf0
      require: True
    ram:
      name: /utility/ram
      id: 0xf1
      require: True

computer_monitor_server:
  ros__parameters:
    frequency: 1.0
    diagnostic_topic: /diagnostics

    cpu_warning_percentage: 90
    cpu_diagnostic_name: /utility/cpu
    cpu_hardware_id: 0xf0

    ram_warning_percentage: 90
    ram_diagnostic_name: /utility/ram
    ram_hardware_id: 0xf1

diagnostic_analyzers:
  ros__parameters:
    path: system
    
    servers:
      type: diagnostic_aggregator/GenericAnalyzer
      path: servers
      contains: ['/servers']

    dbw:
      type: diagnostic_aggregator/GenericAnalyzer
      path: dbw
      contains: ['/dbw']

    sensors:
      type: diagnostic_aggregator/GenericAnalyzer
      path: sensors
      contains: ['/sensors']

    # Not yet added since perception algorithms are not fully finished 
    # algorithms:
    #   type: diagnostic_aggregator/GenericAnalyzer
    #   path: algorithms
    #   contains: ['/algorithms']

    utility:
      type: diagnostic_aggregator/GenericAnalyzer
      path: utility
      contains: ['/utility']