# Rotation of IMU should always be q=1+0i+0j+0k.
# ie orientation hardcoded in IMU register, not here
/servers/static_transform_node:
  ros__parameters:
    frames:
      - 'imu'
      - 'bfly_center'
      - 'bfly_right'
      - 'blfy_left'
      - 'wheelFR'
      - 'wheelFL'
      - 'wheelBR'
      - 'wheelBL'
      - 'hokuyo_front'

    hokuyo_front:
      frame_id: "base_link"
      child_frame_id: "front_lidar"
      translation.x: 2.134
      translation.y: 0.0
      translation.z: 0.0
      rotation.x: 1.0
      rotation.y: 0.0
      rotation.z: 0.0
      rotation.w: 0.0

    imu:
      frame_id: "base_link"
      child_frame_id: "vectornav"
      translation.x: 0.557
      translation.y: -0.1
      translation.z: 1.43
      rotation.x: 0.0
      rotation.y: 0.0
      rotation.z: 0.0
      rotation.w: 1.0
    
    bfly_center:
      frame_id: "base_link"
      child_frame_id: "bfly_center"
      translation.x: 1.0
      translation.y: 0.0
      translation.z: 1.4224
      rotation.x: 0.0
      rotation.y: 0.0
      rotation.z: 0.0
      rotation.w: 1.0

    bfly_right:
      frame_id: "base_link"
      child_frame_id: "bfly_right"
      translation.x: 1.0
      translation.y: -0.4
      translation.z: 1.4224
      rotation.x: 0.0
      rotation.y: 0.0
      rotation.z: 0.0
      rotation.w: 1.0

    blfy_left:
      frame_id: "base_link"
      child_frame_id: "blfy_left"
      translation.x: 1.0
      translation.y: 0.4
      translation.z: 1.4224
      rotation.x: 0.0
      rotation.y: 0.0
      rotation.z: 0.0
      rotation.w: 1.0

    wheelFR:
      frame_id: "base_link"
      child_frame_id: "wheel_fr"
      translation.x: 1.7526
      translation.y: -0.6096
      translation.z: 0
      rotation.x: 0.0
      rotation.y: 0.0
      rotation.z: 0.0
      rotation.w: 1.0

    wheelFL:
      frame_id: "base_link"
      child_frame_id: "wheel_fl"
      translation.x: 1.7526
      translation.y: 0.6096
      translation.z: 0
      rotation.x: 0.0
      rotation.y: 0.0
      rotation.z: 0.0
      rotation.w: 1.0

    wheelBR:
      frame_id: "base_link"
      child_frame_id: "wheel_br"
      translation.x: 0.0
      translation.y: -0.6096
      translation.z: 0
      rotation.x: 0.0
      rotation.y: 0.0
      rotation.z: 0.0
      rotation.w: 1.0

    wheelBL:
      frame_id: "base_link"
      child_frame_id: "wheel_bl"
      translation.x: 0.0
      translation.y: 0.6096
      translation.z: 0
      rotation.x: 0.0
      rotation.y: 0.0
      rotation.z: 0.0
      rotation.w: 1.0